crud/urls.py
from django.urls import path
from . import views

app_name='crud'

urlpatterns = [
    path('', views.task_list_and_create, name='crud_list'), #primero indico la url sin nada, despues la lista que se va a cargar cuando acceda a la url, despues le doy nombre a la url
    path('update_task/<int:task_id>', views.update_task, name='update_task'), #en esta url estoy pidiendo que tambien me indique el id de la tarea
    path('edit_task/<int:task_id>', views.edit_task, name='edit_task'), #url para acceder a editar a task
    path('delete_task/<int:task_id>', views.delete_task, name='delete_task')
]

p001crud/urls.py
from django.contrib import admin#-
from django.urls import path, include#-
urlpatterns = [
    path('admin/', admin.site.urls),
    path('crud/', include('crud.urls', namespace='crud_list')) #defino la url
]

crud/models.py
from django.db import models

class Task(models.Model):  # Llamo a models
    title = models.CharField(max_length=100)  # Titulo - maximo 100 caracteres
    description = models.TextField(blank=True)  # descripcion de las tareas - puede venir en blanco
    is_completed = models.BooleanField(default=False)  # agrego booleano para permitir controlar si la tarea esta completa - por defecto false
    created = models.DateField(auto_now=True)  # sirve para mantener un orden de las tareas cuando las creemos - guarda automaticamente la fecha, saca la fecha de la zona horaria ya definida
     #
    
    class Meta:
        ordering = ['-created']  # creo la columa created que me sirve para ordenar los valores de las tareas creadas

def __str__(self):
    return self.title  # imprime el título de la tarea al momento de crearla - sirve principalmente al programador

crud/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description'] #campos que quiero que el formulario tenga - es mejor hacerlo asi que en cada uno de los archivos de la app
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows':3})
        } # widgets par el forms son para el diseño de cada uno de los inputs

crud/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import Task  # permite comunicarnos con la DB
from .forms import TaskForm

# Create your views here.
# Gestionar peticiones http

def task_list_and_create(request):  # la request es obligatoria 
    if request.method == 'POST':
        form = TaskForm(request.POST)  # guardo todo lo que el user me manda desde el formulario
        if form.is_valid():  # valido si la info es valida
            form.save()  # guardo en la base de datos
            return redirect('crud:crud_list')  # para que se recargue automáticamente una vez tocado el botón guardar
    else:
        form = TaskForm()  # Inicializo el formulario en caso de GET

    #tasks = Task.objects.all()


    #distincion entre tareas creadas y no creadas
    completed_tasks = Task.objects.filter(is_completed=True) # pylint: disable=no-member
    incompleted_tasks = Task.objects.filter(is_completed=False) # pylint: disable=no-member



    return render(request, 'task_list.html', {
        'form': form,
        #'tasks': tasks  
        'completed_tasks': completed_tasks,
        'incompleted_tasks': incompleted_tasks # aquí se pasan los queryset de tareas por separado para cada caso (completadas y no completadas)
    })

def update_task(request, task_id): #para actualizar entre tareas completadas y no completadas
    if request.method == 'POST':
        task = Task.objects.get(id=task_id) #pylint: disable= no-member
        task.is_completed = not task.is_completed
        task.save()
        return redirect('crud:crud_list')
    
def edit_task(request, task_id):
    task = get_object_or_404(Task, id=task_id) 
    initial_data = {
        'title': task.title,
        'description': task.description
    }

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('crud:crud_list')
    else:
        form = TaskForm(instance=task, initial=initial_data)
    return render(request, 'edit_task.html', {'form': form})

def delete_task(request, task_id):
    if request.method == 'POST':
        task = Task.objects.get(id=task_id) #pylint: disable= no-member
        task.delete()
        return redirect('crud:crud_list')

crud/templates/edit_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Editar Tarea</title>
</head>
<body>
    {{task_title}}
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-6">
                <h1>Editando Tarea</h1>
                <form method="post" class="mb-3">
                    {% csrf_token %}
                    <div class="mb-3">
                        {{ form.title.label_tag }}
                        <input type="text" name="title" id="id_title" class="form-control" value="{{ form.initial.title }}">
                    </div>
                    <div class="mb-3">
                        {{ form.description.label_tag }}
                        <textarea name="description" id="id_description" class="form-control">{{ form.initial.description }}</textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Guardar Tarea</button>
                </form>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

crud/templates/task_list.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Lista y Creación de Tareas</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
</head>
<body>
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-6">
                <h1>Agregar Nueva Tarea</h1>
                <form method="post" class="mb-3">
                    {% csrf_token %}
                    <div class="mb-3">
                        {{ form.title.label_tag }}
                        {{ form.title }}
                    </div>
                    <div class="mb-3">
                        {{ form.description.label_tag }}
                        {{ form.description }}
                    </div>
                    <button type="submit" class="btn btn-primary">Agregar Tarea</button>
                </form>
            </div>
            <div class="col-md-6">
                <h2>Tareas No Completadas</h2>
                <ul class="list-group">
                    {% for task in incompleted_tasks %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <div>
                                <strong>{{ task.title }}</strong> {{ task.description }}
                            </div>
                            <div class="d-flex align-items-center">
                                <form action="{% url 'crud:update_task' task.id %}" method="post" class="d-inline">
                                    {% csrf_token %}
                                    <input type="checkbox" name="completed" onchange="this.form.submit()" {% if task.is_completed %} checked {% endif %} class="me-2">
                                </form>

                                <form action="{%url 'crud:edit_task' task.id%}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-light btn-sm me-2">
                                        <i class="bi bi-pen"></i>
                                    </button>
                                </form>  

                                <form action="{%url 'crud:delete_task' task.id%}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger btn-sm">
                                        <i class="bi bi-trash"></i>
                                    </button>
                                </form>
                            </div>
                        </li>
                    {% empty %}
                        <li class="list-group-item">No hay tareas registradas aún.</li>
                    {% endfor %}
                </ul>

                <h2 class="mt-4">Tareas Completadas</h2>
                <ul class="list-group">
                    {% for task in completed_tasks %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <div>
                            <strong>{{ task.title }}</strong> {{ task.description }}
                        </div>
                        <div class="d-flex align-items-center">
                            <form action="{% url 'crud:update_task' task.id %}" method="post" class="d-inline">
                                {% csrf_token %}
                                <input type="checkbox" name="completed" onchange="this.form.submit()" {% if task.is_completed %} checked {% endif %} class="me-2">
                            </form>
                            
                            <form action="{%url 'crud:edit_task' task.id%}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-light btn-sm me-2">
                                    <i class="bi bi-pen"></i>
                                </button>
                            </form>

                            <form action="{%url 'crud:delete_task' task.id%}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger btn-sm">
                                    <i class="bi bi-trash"></i>
                                </button>
                            </form>
                        </div>
                    </li>
                    {% empty %}
                    <li class="list-group-item">No hay tareas completadas aún.</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>